before_install:
  - gem update --system
  - gem --version
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - jruby-head
  - rbx-2
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: ruby-head
